name: Build and Release Docker Image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract Telegraf version
        id: telegraf-version
        run: |
          # Extract version from Dockerfile
          TELEGRAF_VERSION=$(grep -oP '(?<=FROM telegraf:).*' Dockerfile)
          echo "TELEGRAF_VERSION=$TELEGRAF_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/telegraf-smart
          docker build --build-arg TELEGRAF_VERSION=$TELEGRAF_VERSION -t $IMAGE_NAME:$TELEGRAF_VERSION .
          docker tag $IMAGE_NAME:$TELEGRAF_VERSION $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TELEGRAF_VERSION
          docker push $IMAGE_NAME:latest

  create-github-release:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TELEGRAF_VERSION }}
          release_name: Release ${{ env.TELEGRAF_VERSION }}
          body: |
            Docker image: `ghcr.io/${{ github.repository_owner }}/telegraf-smart:${{ env.TELEGRAF_VERSION }}`
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

